// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	Province *string `json:"province"`
	City     *string `json:"city"`
}

type NewAddress struct {
	Province *string `json:"province"`
	City     *string `json:"city"`
}

type NewPeople struct {
	Name    *string     `json:"name"`
	Age     *int        `json:"age"`
	Phone   *string     `json:"phone"`
	Address *NewAddress `json:"address"`
}

type People struct {
	Name    *string  `json:"name"`
	Age     *int     `json:"age"`
	Phone   *string  `json:"phone"`
	Address *Address `json:"address"`
}
