// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: epul.proto

package epul

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type People struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age     int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Phone   string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Address *Address `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *People) Reset() {
	*x = People{}
	if protoimpl.UnsafeEnabled {
		mi := &file_epul_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *People) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*People) ProtoMessage() {}

func (x *People) ProtoReflect() protoreflect.Message {
	mi := &file_epul_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use People.ProtoReflect.Descriptor instead.
func (*People) Descriptor() ([]byte, []int) {
	return file_epul_proto_rawDescGZIP(), []int{0}
}

func (x *People) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *People) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *People) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *People) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Province string `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	City     string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_epul_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_epul_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_epul_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type Peoples struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peoples []*People `protobuf:"bytes,1,rep,name=peoples,proto3" json:"peoples,omitempty"`
}

func (x *Peoples) Reset() {
	*x = Peoples{}
	if protoimpl.UnsafeEnabled {
		mi := &file_epul_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peoples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peoples) ProtoMessage() {}

func (x *Peoples) ProtoReflect() protoreflect.Message {
	mi := &file_epul_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peoples.ProtoReflect.Descriptor instead.
func (*Peoples) Descriptor() ([]byte, []int) {
	return file_epul_proto_rawDescGZIP(), []int{2}
}

func (x *Peoples) GetPeoples() []*People {
	if x != nil {
		return x.Peoples
	}
	return nil
}

var File_epul_proto protoreflect.FileDescriptor

var file_epul_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x70, 0x75, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x06, 0x50, 0x65, 0x6f,
	0x70, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x22, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x39, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x2c,
	0x0a, 0x07, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x07, 0x70, 0x65, 0x6f,
	0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x65, 0x6f,
	0x70, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x73, 0x32, 0x80, 0x01, 0x0a,
	0x0d, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e,
	0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x08, 0x2e, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x20,
	0x0a, 0x0c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x07,
	0x2e, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x1a, 0x07, 0x2e, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65,
	0x12, 0x1d, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x07, 0x2e,
	0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x1a, 0x07, 0x2e, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x42,
	0x18, 0x5a, 0x16, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2d, 0x62, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x65, 0x70, 0x75, 0x6c, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_epul_proto_rawDescOnce sync.Once
	file_epul_proto_rawDescData = file_epul_proto_rawDesc
)

func file_epul_proto_rawDescGZIP() []byte {
	file_epul_proto_rawDescOnce.Do(func() {
		file_epul_proto_rawDescData = protoimpl.X.CompressGZIP(file_epul_proto_rawDescData)
	})
	return file_epul_proto_rawDescData
}

var file_epul_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_epul_proto_goTypes = []interface{}{
	(*People)(nil),        // 0: People
	(*Address)(nil),       // 1: Address
	(*Peoples)(nil),       // 2: Peoples
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_epul_proto_depIdxs = []int32{
	1, // 0: People.address:type_name -> Address
	0, // 1: Peoples.peoples:type_name -> People
	3, // 2: PeopleService.ListPeople:input_type -> google.protobuf.Empty
	0, // 3: PeopleService.DetailPeople:input_type -> People
	0, // 4: PeopleService.AddPeople:input_type -> People
	2, // 5: PeopleService.ListPeople:output_type -> Peoples
	0, // 6: PeopleService.DetailPeople:output_type -> People
	0, // 7: PeopleService.AddPeople:output_type -> People
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_epul_proto_init() }
func file_epul_proto_init() {
	if File_epul_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_epul_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*People); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_epul_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_epul_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peoples); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_epul_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_epul_proto_goTypes,
		DependencyIndexes: file_epul_proto_depIdxs,
		MessageInfos:      file_epul_proto_msgTypes,
	}.Build()
	File_epul_proto = out.File
	file_epul_proto_rawDesc = nil
	file_epul_proto_goTypes = nil
	file_epul_proto_depIdxs = nil
}
